;;; metadata_store_service.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.ML-METADATA.PROTO")
    (cl:defpackage "CL-PROTOBUFS.ML-METADATA.PROTO" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.ML-METADATA.PROTO-RPC")
    (cl:defpackage "CL-PROTOBUFS.ML-METADATA.PROTO-RPC" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.ML-METADATA.PROTO")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'metadata_store_service
    :package "ml_metadata.proto"
     :import '("google/protobuf/field_mask.proto"
              "ml_metadata/proto/metadata_store.proto"))
)


;;; Top-Level messages

(pi:define-message artifact-and-type
    ()
  ;; Fields
  (artifact
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:optional) :json-name "artifact")
  (type
   :index 2 :type cl-protobufs.ml-metadata.proto::artifact-type :kind :message :label (:optional) :json-name "type"))

(pi:define-message artifact-struct-map
    ()
  ;; Nested messages
  ;; Fields
  (pi:define-map properties
     :key-type cl:string
     :value-type artifact-struct
     :json-name "properties"
     :value-kind :message
     :index 1))

(pi:define-message artifact-struct-list
    ()
  ;; Fields
  (elements
   :index 1 :type artifact-struct :kind :message :label (:repeated :list) :json-name "elements"))

(pi:define-message artifact-struct
    ()
  ;; Fields
  (pi:define-oneof value ()
    (artifact
     :index 1 :type artifact-and-type :kind :message :label (:optional) :json-name "artifact")
    (map
     :index 2 :type artifact-struct-map :kind :message :label (:optional) :json-name "map")
    (list
     :index 3 :type artifact-struct-list :kind :message :label (:optional) :json-name "list")))

(pi:define-message put-artifacts-request
    ()
  ;; Nested messages

  (pi:define-message put-artifacts-request.options
      ()
    ;; Fields
    (abort-if-latest-updated-time-changed
     :index 1 :type cl:boolean :kind :scalar :label (:optional) :json-name "abortIfLatestUpdatedTimeChanged"))
  ;; Fields
  (artifacts
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:repeated :list) :json-name "artifacts")
  (options
   :index 2 :type put-artifacts-request.options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions")
  (update-mask
   :index 4 :type cl-protobufs.google.protobuf::field-mask :kind :message :label (:optional) :json-name "updateMask"))

(pi:define-message put-artifacts-response
    ()
  ;; Fields
  (artifact-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "artifactIds"))

(pi:define-message put-artifact-type-request
    ()
  ;; Fields
  (artifact-type
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact-type :kind :message :label (:optional) :json-name "artifactType")
  (can-add-fields
   :index 2 :type cl:boolean :kind :scalar :label (:optional) :json-name "canAddFields")
  (can-omit-fields
   :index 5 :type cl:boolean :kind :scalar :label (:optional) :json-name "canOmitFields")
  (can-delete-fields
   :index 3 :type cl:boolean :kind :scalar :label (:optional) :json-name "canDeleteFields")
  (all-fields-match
   :index 4 :type cl:boolean :kind :scalar :label (:optional) :json-name "allFieldsMatch" :default cl:t)
  (transaction-options
   :index 6 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-artifact-type-response
    ()
  ;; Fields
  (type-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "typeId"))

(pi:define-message put-executions-request
    ()
  ;; Fields
  (executions
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:repeated :list) :json-name "executions")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions")
  (update-mask
   :index 3 :type cl-protobufs.google.protobuf::field-mask :kind :message :label (:optional) :json-name "updateMask"))

(pi:define-message put-executions-response
    ()
  ;; Fields
  (execution-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "executionIds"))

(pi:define-message put-execution-type-request
    ()
  ;; Fields
  (execution-type
   :index 1 :type cl-protobufs.ml-metadata.proto::execution-type :kind :message :label (:optional) :json-name "executionType")
  (can-add-fields
   :index 2 :type cl:boolean :kind :scalar :label (:optional) :json-name "canAddFields")
  (can-omit-fields
   :index 5 :type cl:boolean :kind :scalar :label (:optional) :json-name "canOmitFields")
  (can-delete-fields
   :index 3 :type cl:boolean :kind :scalar :label (:optional) :json-name "canDeleteFields")
  (all-fields-match
   :index 4 :type cl:boolean :kind :scalar :label (:optional) :json-name "allFieldsMatch" :default cl:t)
  (transaction-options
   :index 6 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-execution-type-response
    ()
  ;; Fields
  (type-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "typeId"))

(pi:define-message put-events-request
    ()
  ;; Fields
  (events
   :index 1 :type cl-protobufs.ml-metadata.proto::event :kind :message :label (:repeated :list) :json-name "events")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-events-response
    ())

(pi:define-message put-execution-request
    ()
  ;; Nested messages

  (pi:define-message put-execution-request.artifact-and-event
      ()
    ;; Fields
    (artifact
     :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:optional) :json-name "artifact")
    (event
     :index 2 :type cl-protobufs.ml-metadata.proto::event :kind :message :label (:optional) :json-name "event"))

  (pi:define-message put-execution-request.options
      ()
    ;; Fields
    (reuse-context-if-already-exist
     :index 1 :type cl:boolean :kind :scalar :label (:optional) :json-name "reuseContextIfAlreadyExist")
    (reuse-artifact-if-already-exist-by-external-id
     :index 2 :type cl:boolean :kind :scalar :label (:optional) :json-name "reuseArtifactIfAlreadyExistByExternalId")
    (force-update-time
     :index 3 :type cl:boolean :kind :scalar :label (:optional) :json-name "forceUpdateTime")
    (force-reuse-context
     :index 4 :type cl:boolean :kind :scalar :label (:optional) :json-name "forceReuseContext"))
  ;; Fields
  (execution
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:optional) :json-name "execution")
  (artifact-event-pairs
   :index 2 :type put-execution-request.artifact-and-event :kind :message :label (:repeated :list) :json-name "artifactEventPairs")
  (contexts
   :index 3 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts")
  (options
   :index 4 :type put-execution-request.options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 5 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-execution-response
    ()
  ;; Fields
  (execution-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "executionId")
  (artifact-ids
   :index 2 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "artifactIds")
  (context-ids
   :index 3 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "contextIds"))

(pi:define-message put-lineage-subgraph-request
    ()
  ;; Nested messages

  (pi:define-message put-lineage-subgraph-request.event-edge
      ()
    ;; Fields
    (execution-index
     :index 1 :type cl-protobufs:int32 :kind :scalar :label (:optional) :json-name "executionIndex")
    (artifact-index
     :index 2 :type cl-protobufs:int32 :kind :scalar :label (:optional) :json-name "artifactIndex")
    (event
     :index 3 :type cl-protobufs.ml-metadata.proto::event :kind :message :label (:optional) :json-name "event"))

  (pi:define-message put-lineage-subgraph-request.options
      ()
    ;; Fields
    (reuse-context-if-already-exist
     :index 1 :type cl:boolean :kind :scalar :label (:optional) :json-name "reuseContextIfAlreadyExist")
    (reuse-artifact-if-already-exist-by-external-id
     :index 2 :type cl:boolean :kind :scalar :label (:optional) :json-name "reuseArtifactIfAlreadyExistByExternalId"))
  ;; Fields
  (executions
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:repeated :list) :json-name "executions")
  (artifacts
   :index 2 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:repeated :list) :json-name "artifacts")
  (contexts
   :index 3 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts")
  (event-edges
   :index 4 :type put-lineage-subgraph-request.event-edge :kind :message :label (:repeated :list) :json-name "eventEdges")
  (options
   :index 5 :type put-lineage-subgraph-request.options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 6 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-lineage-subgraph-response
    ()
  ;; Fields
  (execution-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "executionIds" :packed cl:t)
  (artifact-ids
   :index 2 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "artifactIds" :packed cl:t)
  (context-ids
   :index 3 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "contextIds" :packed cl:t))

(pi:define-message put-types-request
    ()
  ;; Fields
  (artifact-types
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact-type :kind :message :label (:repeated :list) :json-name "artifactTypes")
  (execution-types
   :index 2 :type cl-protobufs.ml-metadata.proto::execution-type :kind :message :label (:repeated :list) :json-name "executionTypes")
  (context-types
   :index 3 :type cl-protobufs.ml-metadata.proto::context-type :kind :message :label (:repeated :list) :json-name "contextTypes")
  (can-add-fields
   :index 4 :type cl:boolean :kind :scalar :label (:optional) :json-name "canAddFields")
  (can-omit-fields
   :index 7 :type cl:boolean :kind :scalar :label (:optional) :json-name "canOmitFields")
  (can-delete-fields
   :index 5 :type cl:boolean :kind :scalar :label (:optional) :json-name "canDeleteFields")
  (all-fields-match
   :index 6 :type cl:boolean :kind :scalar :label (:optional) :json-name "allFieldsMatch" :default cl:t)
  (transaction-options
   :index 8 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-types-response
    ()
  ;; Fields
  (artifact-type-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "artifactTypeIds")
  (execution-type-ids
   :index 2 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "executionTypeIds")
  (context-type-ids
   :index 3 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "contextTypeIds"))

(pi:define-message put-context-type-request
    ()
  ;; Fields
  (context-type
   :index 1 :type cl-protobufs.ml-metadata.proto::context-type :kind :message :label (:optional) :json-name "contextType")
  (can-add-fields
   :index 2 :type cl:boolean :kind :scalar :label (:optional) :json-name "canAddFields")
  (can-omit-fields
   :index 5 :type cl:boolean :kind :scalar :label (:optional) :json-name "canOmitFields")
  (can-delete-fields
   :index 3 :type cl:boolean :kind :scalar :label (:optional) :json-name "canDeleteFields")
  (all-fields-match
   :index 4 :type cl:boolean :kind :scalar :label (:optional) :json-name "allFieldsMatch" :default cl:t)
  (transaction-options
   :index 6 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-context-type-response
    ()
  ;; Fields
  (type-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "typeId"))

(pi:define-message put-contexts-request
    ()
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions")
  (update-mask
   :index 3 :type cl-protobufs.google.protobuf::field-mask :kind :message :label (:optional) :json-name "updateMask"))

(pi:define-message put-contexts-response
    ()
  ;; Fields
  (context-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "contextIds"))

(pi:define-message put-attributions-and-associations-request
    ()
  ;; Fields
  (attributions
   :index 1 :type cl-protobufs.ml-metadata.proto::attribution :kind :message :label (:repeated :list) :json-name "attributions")
  (associations
   :index 2 :type cl-protobufs.ml-metadata.proto::association :kind :message :label (:repeated :list) :json-name "associations")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-attributions-and-associations-response
    ())

(pi:define-message put-parent-contexts-request
    ()
  ;; Fields
  (parent-contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::parent-context :kind :message :label (:repeated :list) :json-name "parentContexts")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message put-parent-contexts-response
    ())

(pi:define-message get-artifacts-by-type-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (type-version
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (options
   :index 3 :type cl-protobufs.ml-metadata.proto::list-operation-options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 4 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifacts-by-type-response
    ()
  ;; Fields
  (artifacts
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:repeated :list) :json-name "artifacts")
  (next-page-token
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "nextPageToken"))

(pi:define-message get-artifact-by-type-and-name-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (type-version
   :index 3 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (artifact-name
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "artifactName")
  (transaction-options
   :index 4 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifact-by-type-and-name-response
    ()
  ;; Fields
  (artifact
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:optional) :json-name "artifact"))

(pi:define-message get-artifacts-by-id-request
    (
     :name "GetArtifactsByIDRequest")
  ;; Fields
  (artifact-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "artifactIds")
  (populate-artifact-types
   :index 3 :type cl:boolean :kind :scalar :label (:optional) :json-name "populateArtifactTypes" :default cl:nil)
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifacts-by-id-response
    (
     :name "GetArtifactsByIDResponse")
  ;; Fields
  (artifacts
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:repeated :list) :json-name "artifacts")
  (artifact-types
   :index 2 :type cl-protobufs.ml-metadata.proto::artifact-type :kind :message :label (:repeated :list) :json-name "artifactTypes"))

(pi:define-message get-artifacts-request
    ()
  ;; Fields
  (options
   :index 1 :type cl-protobufs.ml-metadata.proto::list-operation-options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifacts-response
    ()
  ;; Fields
  (artifacts
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:repeated :list) :json-name "artifacts")
  (next-page-token
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "nextPageToken"))

(pi:define-message get-artifacts-by-uri-request
    (
     :name "GetArtifactsByURIRequest")
  ;; Fields
  (uris
   :index 2 :type cl:string :kind :scalar :label (:repeated :list) :json-name "uris")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifacts-by-uri-response
    (
     :name "GetArtifactsByURIResponse")
  ;; Fields
  (artifacts
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:repeated :list) :json-name "artifacts"))

(pi:define-message get-executions-request
    ()
  ;; Fields
  (options
   :index 1 :type cl-protobufs.ml-metadata.proto::list-operation-options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-executions-response
    ()
  ;; Fields
  (executions
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:repeated :list) :json-name "executions")
  (next-page-token
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "nextPageToken"))

(pi:define-message get-artifact-type-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (type-version
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifact-type-response
    ()
  ;; Fields
  (artifact-type
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact-type :kind :message :label (:optional) :json-name "artifactType"))

(pi:define-message get-artifact-types-request
    ()
  ;; Fields
  (transaction-options
   :index 1 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifact-types-response
    ()
  ;; Fields
  (artifact-types
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact-type :kind :message :label (:repeated :list) :json-name "artifactTypes"))

(pi:define-message get-execution-types-request
    ()
  ;; Fields
  (transaction-options
   :index 1 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-execution-types-response
    ()
  ;; Fields
  (execution-types
   :index 1 :type cl-protobufs.ml-metadata.proto::execution-type :kind :message :label (:repeated :list) :json-name "executionTypes"))

(pi:define-message get-context-types-request
    ()
  ;; Fields
  (transaction-options
   :index 1 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-context-types-response
    ()
  ;; Fields
  (context-types
   :index 1 :type cl-protobufs.ml-metadata.proto::context-type :kind :message :label (:repeated :list) :json-name "contextTypes"))

(pi:define-message get-artifacts-by-external-ids-request
    ()
  ;; Fields
  (external-ids
   :index 1 :type cl:string :kind :scalar :label (:repeated :list) :json-name "externalIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifacts-by-external-ids-response
    ()
  ;; Fields
  (artifacts
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:repeated :list) :json-name "artifacts"))

(pi:define-message get-executions-by-external-ids-request
    ()
  ;; Fields
  (external-ids
   :index 1 :type cl:string :kind :scalar :label (:repeated :list) :json-name "externalIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-executions-by-external-ids-response
    ()
  ;; Fields
  (executions
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:repeated :list) :json-name "executions"))

(pi:define-message get-contexts-by-external-ids-request
    ()
  ;; Fields
  (external-ids
   :index 1 :type cl:string :kind :scalar :label (:repeated :list) :json-name "externalIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-contexts-by-external-ids-response
    ()
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts"))

(pi:define-message get-artifact-types-by-external-ids-request
    ()
  ;; Fields
  (external-ids
   :index 1 :type cl:string :kind :scalar :label (:repeated :list) :json-name "externalIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifact-types-by-external-ids-response
    ()
  ;; Fields
  (artifact-types
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact-type :kind :message :label (:repeated :list) :json-name "artifactTypes"))

(pi:define-message get-execution-types-by-external-ids-request
    ()
  ;; Fields
  (external-ids
   :index 1 :type cl:string :kind :scalar :label (:repeated :list) :json-name "externalIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-execution-types-by-external-ids-response
    ()
  ;; Fields
  (execution-types
   :index 1 :type cl-protobufs.ml-metadata.proto::execution-type :kind :message :label (:repeated :list) :json-name "executionTypes"))

(pi:define-message get-context-types-by-external-ids-request
    ()
  ;; Fields
  (external-ids
   :index 1 :type cl:string :kind :scalar :label (:repeated :list) :json-name "externalIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-context-types-by-external-ids-response
    ()
  ;; Fields
  (context-types
   :index 1 :type cl-protobufs.ml-metadata.proto::context-type :kind :message :label (:repeated :list) :json-name "contextTypes"))

(pi:define-message get-executions-by-type-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (type-version
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (options
   :index 3 :type cl-protobufs.ml-metadata.proto::list-operation-options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 4 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-executions-by-type-response
    ()
  ;; Fields
  (executions
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:repeated :list) :json-name "executions")
  (next-page-token
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "nextPageToken"))

(pi:define-message get-execution-by-type-and-name-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (type-version
   :index 3 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (execution-name
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "executionName")
  (transaction-options
   :index 4 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-execution-by-type-and-name-response
    ()
  ;; Fields
  (execution
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:optional) :json-name "execution"))

(pi:define-message get-executions-by-id-request
    (
     :name "GetExecutionsByIDRequest")
  ;; Fields
  (execution-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "executionIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-executions-by-id-response
    (
     :name "GetExecutionsByIDResponse")
  ;; Fields
  (executions
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:repeated :list) :json-name "executions"))

(pi:define-message get-execution-type-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (type-version
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-execution-type-response
    ()
  ;; Fields
  (execution-type
   :index 1 :type cl-protobufs.ml-metadata.proto::execution-type :kind :message :label (:optional) :json-name "executionType"))

(pi:define-message get-events-by-execution-i-ds-request
    ()
  ;; Fields
  (execution-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "executionIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-events-by-execution-i-ds-response
    ()
  ;; Fields
  (events
   :index 1 :type cl-protobufs.ml-metadata.proto::event :kind :message :label (:repeated :list) :json-name "events"))

(pi:define-message get-events-by-artifact-i-ds-request
    ()
  ;; Fields
  (artifact-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "artifactIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-events-by-artifact-i-ds-response
    ()
  ;; Fields
  (events
   :index 1 :type cl-protobufs.ml-metadata.proto::event :kind :message :label (:repeated :list) :json-name "events"))

(pi:define-message get-artifact-types-by-id-request
    (
     :name "GetArtifactTypesByIDRequest")
  ;; Fields
  (type-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "typeIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifact-types-by-id-response
    (
     :name "GetArtifactTypesByIDResponse")
  ;; Fields
  (artifact-types
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact-type :kind :message :label (:repeated :list) :json-name "artifactTypes"))

(pi:define-message get-execution-types-by-id-request
    (
     :name "GetExecutionTypesByIDRequest")
  ;; Fields
  (type-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "typeIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-execution-types-by-id-response
    (
     :name "GetExecutionTypesByIDResponse")
  ;; Fields
  (execution-types
   :index 1 :type cl-protobufs.ml-metadata.proto::execution-type :kind :message :label (:repeated :list) :json-name "executionTypes"))

(pi:define-message get-context-type-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (type-version
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-context-type-response
    ()
  ;; Fields
  (context-type
   :index 1 :type cl-protobufs.ml-metadata.proto::context-type :kind :message :label (:optional) :json-name "contextType"))

(pi:define-message get-context-types-by-id-request
    (
     :name "GetContextTypesByIDRequest")
  ;; Fields
  (type-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "typeIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-context-types-by-id-response
    (
     :name "GetContextTypesByIDResponse")
  ;; Fields
  (context-types
   :index 1 :type cl-protobufs.ml-metadata.proto::context-type :kind :message :label (:repeated :list) :json-name "contextTypes"))

(pi:define-message get-contexts-request
    ()
  ;; Fields
  (options
   :index 1 :type cl-protobufs.ml-metadata.proto::list-operation-options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-contexts-response
    ()
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts")
  (next-page-token
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "nextPageToken"))

(pi:define-message get-contexts-by-type-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (options
   :index 2 :type cl-protobufs.ml-metadata.proto::list-operation-options :kind :message :label (:optional) :json-name "options")
  (type-version
   :index 3 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (transaction-options
   :index 4 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-contexts-by-type-response
    ()
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts")
  (next-page-token
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "nextPageToken"))

(pi:define-message get-context-by-type-and-name-request
    ()
  ;; Fields
  (type-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :json-name "typeName")
  (type-version
   :index 3 :type cl:string :kind :scalar :label (:optional) :json-name "typeVersion")
  (context-name
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "contextName")
  (transaction-options
   :index 4 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-context-by-type-and-name-response
    ()
  ;; Fields
  (context
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:optional) :json-name "context"))

(pi:define-message get-contexts-by-id-request
    (
     :name "GetContextsByIDRequest")
  ;; Fields
  (context-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "contextIds")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-contexts-by-id-response
    (
     :name "GetContextsByIDResponse")
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts"))

(pi:define-message get-contexts-by-artifact-request
    ()
  ;; Fields
  (artifact-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "artifactId")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-contexts-by-artifact-response
    ()
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts"))

(pi:define-message get-contexts-by-execution-request
    ()
  ;; Fields
  (execution-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "executionId")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-contexts-by-execution-response
    ()
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts"))

(pi:define-message get-parent-contexts-by-context-request
    ()
  ;; Fields
  (context-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "contextId")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-parent-contexts-by-context-response
    ()
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts"))

(pi:define-message get-children-contexts-by-context-request
    ()
  ;; Fields
  (context-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "contextId")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-children-contexts-by-context-response
    ()
  ;; Fields
  (contexts
   :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "contexts"))

(pi:define-message get-parent-contexts-by-contexts-request
    ()
  ;; Fields
  (context-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "contextIds" :packed cl:t)
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-parent-contexts-by-contexts-response
    ()
  ;; Nested messages

  (pi:define-message get-parent-contexts-by-contexts-response.parent-contexts-per-child
      ()
    ;; Fields
    (parent-contexts
     :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "parentContexts"))
  ;; Fields
  (pi:define-map contexts
     :key-type cl-protobufs:int64
     :value-type get-parent-contexts-by-contexts-response.parent-contexts-per-child
     :json-name "contexts"
     :value-kind :message
     :index 2))

(pi:define-message get-children-contexts-by-contexts-request
    ()
  ;; Fields
  (context-ids
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:repeated :list) :json-name "contextIds" :packed cl:t)
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-children-contexts-by-contexts-response
    ()
  ;; Nested messages

  (pi:define-message get-children-contexts-by-contexts-response.children-contexts-per-parent
      ()
    ;; Fields
    (children-contexts
     :index 1 :type cl-protobufs.ml-metadata.proto::context :kind :message :label (:repeated :list) :json-name "childrenContexts"))
  ;; Fields
  (pi:define-map contexts
     :key-type cl-protobufs:int64
     :value-type get-children-contexts-by-contexts-response.children-contexts-per-parent
     :json-name "contexts"
     :value-kind :message
     :index 2))

(pi:define-message get-artifacts-by-context-request
    ()
  ;; Fields
  (context-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "contextId")
  (options
   :index 2 :type cl-protobufs.ml-metadata.proto::list-operation-options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-artifacts-by-context-response
    ()
  ;; Fields
  (artifacts
   :index 1 :type cl-protobufs.ml-metadata.proto::artifact :kind :message :label (:repeated :list) :json-name "artifacts")
  (next-page-token
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "nextPageToken"))

(pi:define-message get-executions-by-context-request
    ()
  ;; Fields
  (context-id
   :index 1 :type cl-protobufs:int64 :kind :scalar :label (:optional) :json-name "contextId")
  (options
   :index 2 :type cl-protobufs.ml-metadata.proto::list-operation-options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-executions-by-context-response
    ()
  ;; Fields
  (executions
   :index 1 :type cl-protobufs.ml-metadata.proto::execution :kind :message :label (:repeated :list) :json-name "executions")
  (next-page-token
   :index 2 :type cl:string :kind :scalar :label (:optional) :json-name "nextPageToken")
  (transaction-options
   :index 3 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-lineage-graph-request
    ()
  ;; Fields
  (options
   :index 1 :type cl-protobufs.ml-metadata.proto::lineage-graph-query-options :kind :message :label (:optional) :json-name "options")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-lineage-graph-response
    ()
  ;; Fields
  (subgraph
   :index 1 :type cl-protobufs.ml-metadata.proto::lineage-graph :kind :message :label (:optional) :json-name "subgraph"))

(pi:define-message get-lineage-subgraph-request
    ()
  ;; Fields
  (lineage-subgraph-query-options
   :index 1 :type cl-protobufs.ml-metadata.proto::lineage-subgraph-query-options :kind :message :label (:optional) :json-name "lineageSubgraphQueryOptions")
  (read-mask
   :index 3 :type cl-protobufs.google.protobuf::field-mask :kind :message :label (:optional) :json-name "readMask")
  (transaction-options
   :index 2 :type cl-protobufs.ml-metadata.proto::transaction-options :kind :message :label (:optional) :json-name "transactionOptions"))

(pi:define-message get-lineage-subgraph-response
    ()
  ;; Fields
  (lineage-subgraph
   :index 1 :type cl-protobufs.ml-metadata.proto::lineage-graph :kind :message :label (:optional) :json-name "lineageSubgraph"))

;;; Services
(pi:define-service metadata-store-service
    (:source-location #P"metadata_store_service.proto")
  (put-artifact-type (
    put-artifact-type-request =>
    put-artifact-type-response))
  (put-execution-type (
    put-execution-type-request =>
    put-execution-type-response))
  (put-context-type (
    put-context-type-request =>
    put-context-type-response))
  (put-types (
    put-types-request =>
    put-types-response))
  (put-artifacts (
    put-artifacts-request =>
    put-artifacts-response))
  (put-executions (
    put-executions-request =>
    put-executions-response))
  (put-events (
    put-events-request =>
    put-events-response))
  (put-execution (
    put-execution-request =>
    put-execution-response))
  (put-lineage-subgraph (
    put-lineage-subgraph-request =>
    put-lineage-subgraph-response))
  (put-contexts (
    put-contexts-request =>
    put-contexts-response))
  (put-attributions-and-associations (
    put-attributions-and-associations-request =>
    put-attributions-and-associations-response))
  (put-parent-contexts (
    put-parent-contexts-request =>
    put-parent-contexts-response))
  (get-artifact-type (
    get-artifact-type-request =>
    get-artifact-type-response))
  (get-artifact-types-by-id (
    (get-artifact-types-by-id-request :name "ml_metadata.proto.GetArtifactTypesByIDRequest") =>
    (get-artifact-types-by-id-response :name "ml_metadata.proto.GetArtifactTypesByIDResponse"))
    :name "GetArtifactTypesByID")
  (get-artifact-types (
    get-artifact-types-request =>
    get-artifact-types-response))
  (get-execution-type (
    get-execution-type-request =>
    get-execution-type-response))
  (get-execution-types-by-id (
    (get-execution-types-by-id-request :name "ml_metadata.proto.GetExecutionTypesByIDRequest") =>
    (get-execution-types-by-id-response :name "ml_metadata.proto.GetExecutionTypesByIDResponse"))
    :name "GetExecutionTypesByID")
  (get-execution-types (
    get-execution-types-request =>
    get-execution-types-response))
  (get-context-type (
    get-context-type-request =>
    get-context-type-response))
  (get-context-types-by-id (
    (get-context-types-by-id-request :name "ml_metadata.proto.GetContextTypesByIDRequest") =>
    (get-context-types-by-id-response :name "ml_metadata.proto.GetContextTypesByIDResponse"))
    :name "GetContextTypesByID")
  (get-context-types (
    get-context-types-request =>
    get-context-types-response))
  (get-artifacts (
    get-artifacts-request =>
    get-artifacts-response))
  (get-executions (
    get-executions-request =>
    get-executions-response))
  (get-contexts (
    get-contexts-request =>
    get-contexts-response))
  (get-artifacts-by-id (
    (get-artifacts-by-id-request :name "ml_metadata.proto.GetArtifactsByIDRequest") =>
    (get-artifacts-by-id-response :name "ml_metadata.proto.GetArtifactsByIDResponse"))
    :name "GetArtifactsByID")
  (get-executions-by-id (
    (get-executions-by-id-request :name "ml_metadata.proto.GetExecutionsByIDRequest") =>
    (get-executions-by-id-response :name "ml_metadata.proto.GetExecutionsByIDResponse"))
    :name "GetExecutionsByID")
  (get-contexts-by-id (
    (get-contexts-by-id-request :name "ml_metadata.proto.GetContextsByIDRequest") =>
    (get-contexts-by-id-response :name "ml_metadata.proto.GetContextsByIDResponse"))
    :name "GetContextsByID")
  (get-artifacts-by-type (
    get-artifacts-by-type-request =>
    get-artifacts-by-type-response))
  (get-executions-by-type (
    get-executions-by-type-request =>
    get-executions-by-type-response))
  (get-contexts-by-type (
    get-contexts-by-type-request =>
    get-contexts-by-type-response))
  (get-artifact-by-type-and-name (
    get-artifact-by-type-and-name-request =>
    get-artifact-by-type-and-name-response))
  (get-execution-by-type-and-name (
    get-execution-by-type-and-name-request =>
    get-execution-by-type-and-name-response))
  (get-context-by-type-and-name (
    get-context-by-type-and-name-request =>
    get-context-by-type-and-name-response))
  (get-artifacts-by-uri (
    (get-artifacts-by-uri-request :name "ml_metadata.proto.GetArtifactsByURIRequest") =>
    (get-artifacts-by-uri-response :name "ml_metadata.proto.GetArtifactsByURIResponse"))
    :name "GetArtifactsByURI")
  (get-events-by-execution-i-ds (
    get-events-by-execution-i-ds-request =>
    get-events-by-execution-i-ds-response))
  (get-events-by-artifact-i-ds (
    get-events-by-artifact-i-ds-request =>
    get-events-by-artifact-i-ds-response))
  (get-artifacts-by-external-ids (
    get-artifacts-by-external-ids-request =>
    get-artifacts-by-external-ids-response))
  (get-executions-by-external-ids (
    get-executions-by-external-ids-request =>
    get-executions-by-external-ids-response))
  (get-contexts-by-external-ids (
    get-contexts-by-external-ids-request =>
    get-contexts-by-external-ids-response))
  (get-artifact-types-by-external-ids (
    get-artifact-types-by-external-ids-request =>
    get-artifact-types-by-external-ids-response))
  (get-execution-types-by-external-ids (
    get-execution-types-by-external-ids-request =>
    get-execution-types-by-external-ids-response))
  (get-context-types-by-external-ids (
    get-context-types-by-external-ids-request =>
    get-context-types-by-external-ids-response))
  (get-contexts-by-artifact (
    get-contexts-by-artifact-request =>
    get-contexts-by-artifact-response))
  (get-contexts-by-execution (
    get-contexts-by-execution-request =>
    get-contexts-by-execution-response))
  (get-parent-contexts-by-context (
    get-parent-contexts-by-context-request =>
    get-parent-contexts-by-context-response))
  (get-children-contexts-by-context (
    get-children-contexts-by-context-request =>
    get-children-contexts-by-context-response))
  (get-parent-contexts-by-contexts (
    get-parent-contexts-by-contexts-request =>
    get-parent-contexts-by-contexts-response))
  (get-children-contexts-by-contexts (
    get-children-contexts-by-contexts-request =>
    get-children-contexts-by-contexts-response))
  (get-artifacts-by-context (
    get-artifacts-by-context-request =>
    get-artifacts-by-context-response))
  (get-executions-by-context (
    get-executions-by-context-request =>
    get-executions-by-context-response))
  (get-lineage-graph (
    get-lineage-graph-request =>
    get-lineage-graph-response)
    :options ("deprecated" cl:t))
  (get-lineage-subgraph (
    get-lineage-subgraph-request =>
    get-lineage-subgraph-response)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:add-file-descriptor #P"metadata_store_service.proto" 'metadata_store_service)
)

(cl:export '(abort-if-latest-updated-time-changed
             all-fields-match
             artifact
             artifact-and-type
             artifact-event-pairs
             artifact-id
             artifact-ids
             artifact-index
             artifact-name
             artifact-struct
             artifact-struct-list
             artifact-struct-map
             artifact-struct-map.properties-entry
             artifact-type
             artifact-type-ids
             artifact-types
             artifacts
             associations
             attributions
             can-add-fields
             can-delete-fields
             can-omit-fields
             children-contexts
             context
             context-id
             context-ids
             context-name
             context-type
             context-type-ids
             context-types
             contexts
             elements
             event
             event-edges
             events
             execution
             execution-id
             execution-ids
             execution-index
             execution-name
             execution-type
             execution-type-ids
             execution-types
             executions
             external-ids
             force-reuse-context
             force-update-time
             get-artifact-by-type-and-name-request
             get-artifact-by-type-and-name-response
             get-artifact-type-request
             get-artifact-type-response
             get-artifact-types-by-external-ids-request
             get-artifact-types-by-external-ids-response
             get-artifact-types-by-id-request
             get-artifact-types-by-id-response
             get-artifact-types-request
             get-artifact-types-response
             get-artifacts-by-context-request
             get-artifacts-by-context-response
             get-artifacts-by-external-ids-request
             get-artifacts-by-external-ids-response
             get-artifacts-by-id-request
             get-artifacts-by-id-response
             get-artifacts-by-type-request
             get-artifacts-by-type-response
             get-artifacts-by-uri-request
             get-artifacts-by-uri-response
             get-artifacts-request
             get-artifacts-response
             get-children-contexts-by-context-request
             get-children-contexts-by-context-response
             get-children-contexts-by-contexts-request
             get-children-contexts-by-contexts-response
             get-children-contexts-by-contexts-response.children-contexts-per-parent
             get-children-contexts-by-contexts-response.contexts-entry
             get-context-by-type-and-name-request
             get-context-by-type-and-name-response
             get-context-type-request
             get-context-type-response
             get-context-types-by-external-ids-request
             get-context-types-by-external-ids-response
             get-context-types-by-id-request
             get-context-types-by-id-response
             get-context-types-request
             get-context-types-response
             get-contexts-by-artifact-request
             get-contexts-by-artifact-response
             get-contexts-by-execution-request
             get-contexts-by-execution-response
             get-contexts-by-external-ids-request
             get-contexts-by-external-ids-response
             get-contexts-by-id-request
             get-contexts-by-id-response
             get-contexts-by-type-request
             get-contexts-by-type-response
             get-contexts-request
             get-contexts-response
             get-events-by-artifact-i-ds-request
             get-events-by-artifact-i-ds-response
             get-events-by-execution-i-ds-request
             get-events-by-execution-i-ds-response
             get-execution-by-type-and-name-request
             get-execution-by-type-and-name-response
             get-execution-type-request
             get-execution-type-response
             get-execution-types-by-external-ids-request
             get-execution-types-by-external-ids-response
             get-execution-types-by-id-request
             get-execution-types-by-id-response
             get-execution-types-request
             get-execution-types-response
             get-executions-by-context-request
             get-executions-by-context-response
             get-executions-by-external-ids-request
             get-executions-by-external-ids-response
             get-executions-by-id-request
             get-executions-by-id-response
             get-executions-by-type-request
             get-executions-by-type-response
             get-executions-request
             get-executions-response
             get-lineage-graph-request
             get-lineage-graph-response
             get-lineage-subgraph-request
             get-lineage-subgraph-response
             get-parent-contexts-by-context-request
             get-parent-contexts-by-context-response
             get-parent-contexts-by-contexts-request
             get-parent-contexts-by-contexts-response
             get-parent-contexts-by-contexts-response.contexts-entry
             get-parent-contexts-by-contexts-response.parent-contexts-per-child
             key
             lineage-subgraph
             lineage-subgraph-query-options
             list
             map
             metadata-store-service
             metadata_store_service
             next-page-token
             options
             parent-contexts
             populate-artifact-types
             properties
             put-artifact-type-request
             put-artifact-type-response
             put-artifacts-request
             put-artifacts-request.options
             put-artifacts-response
             put-attributions-and-associations-request
             put-attributions-and-associations-response
             put-context-type-request
             put-context-type-response
             put-contexts-request
             put-contexts-response
             put-events-request
             put-events-response
             put-execution-request
             put-execution-request.artifact-and-event
             put-execution-request.options
             put-execution-response
             put-execution-type-request
             put-execution-type-response
             put-executions-request
             put-executions-response
             put-lineage-subgraph-request
             put-lineage-subgraph-request.event-edge
             put-lineage-subgraph-request.options
             put-lineage-subgraph-response
             put-parent-contexts-request
             put-parent-contexts-response
             put-types-request
             put-types-response
             read-mask
             reuse-artifact-if-already-exist-by-external-id
             reuse-context-if-already-exist
             subgraph
             transaction-options
             type
             type-id
             type-ids
             type-name
             type-version
             update-mask
             uris
             value))

(cl:in-package "CL-PROTOBUFS.ML-METADATA.PROTO-RPC")

(cl:export '(call-put-artifact-type
             put-artifact-type
             call-put-execution-type
             put-execution-type
             call-put-context-type
             put-context-type
             call-put-types
             put-types
             call-put-artifacts
             put-artifacts
             call-put-executions
             put-executions
             call-put-events
             put-events
             call-put-execution
             put-execution
             call-put-lineage-subgraph
             put-lineage-subgraph
             call-put-contexts
             put-contexts
             call-put-attributions-and-associations
             put-attributions-and-associations
             call-put-parent-contexts
             put-parent-contexts
             call-get-artifact-type
             get-artifact-type
             call-get-artifact-types-by-id
             get-artifact-types-by-id
             call-get-artifact-types
             get-artifact-types
             call-get-execution-type
             get-execution-type
             call-get-execution-types-by-id
             get-execution-types-by-id
             call-get-execution-types
             get-execution-types
             call-get-context-type
             get-context-type
             call-get-context-types-by-id
             get-context-types-by-id
             call-get-context-types
             get-context-types
             call-get-artifacts
             get-artifacts
             call-get-executions
             get-executions
             call-get-contexts
             get-contexts
             call-get-artifacts-by-id
             get-artifacts-by-id
             call-get-executions-by-id
             get-executions-by-id
             call-get-contexts-by-id
             get-contexts-by-id
             call-get-artifacts-by-type
             get-artifacts-by-type
             call-get-executions-by-type
             get-executions-by-type
             call-get-contexts-by-type
             get-contexts-by-type
             call-get-artifact-by-type-and-name
             get-artifact-by-type-and-name
             call-get-execution-by-type-and-name
             get-execution-by-type-and-name
             call-get-context-by-type-and-name
             get-context-by-type-and-name
             call-get-artifacts-by-uri
             get-artifacts-by-uri
             call-get-events-by-execution-i-ds
             get-events-by-execution-i-ds
             call-get-events-by-artifact-i-ds
             get-events-by-artifact-i-ds
             call-get-artifacts-by-external-ids
             get-artifacts-by-external-ids
             call-get-executions-by-external-ids
             get-executions-by-external-ids
             call-get-contexts-by-external-ids
             get-contexts-by-external-ids
             call-get-artifact-types-by-external-ids
             get-artifact-types-by-external-ids
             call-get-execution-types-by-external-ids
             get-execution-types-by-external-ids
             call-get-context-types-by-external-ids
             get-context-types-by-external-ids
             call-get-contexts-by-artifact
             get-contexts-by-artifact
             call-get-contexts-by-execution
             get-contexts-by-execution
             call-get-parent-contexts-by-context
             get-parent-contexts-by-context
             call-get-children-contexts-by-context
             get-children-contexts-by-context
             call-get-parent-contexts-by-contexts
             get-parent-contexts-by-contexts
             call-get-children-contexts-by-contexts
             get-children-contexts-by-contexts
             call-get-artifacts-by-context
             get-artifacts-by-context
             call-get-executions-by-context
             get-executions-by-context
             call-get-lineage-graph
             get-lineage-graph
             call-get-lineage-subgraph
             get-lineage-subgraph))
